# Generated by Django 5.2 on 2025-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text="The note's title.", max_length=200)),
                ('content', models.TextField(blank=True, help_text="The note's content.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the note was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the note was last updated.')),
            ],
        ),
    ]
